// ============================================================
// MyHapps Labs — Content Data Store
// Edit this file to update all site content without touching index.html
// ============================================================
window.SITE_DATA = {

  apps: [
    {
      id: "myhapps",
      name: "MyHapps",
      icon: "📲",
      tags: ["Free","Android","Offline","v1.0"],
      short: "The ultimate sandbox for your mobile device. Write HTML, CSS, JS, and JSON to build and run multiple offline apps with Local LLM AI support.",
      link: "https://play.google.com/store/apps/details?id=com.myhappslabs.myhapps",
      about: [
        "MyHapps transforms your phone into a complete development sandbox. Create full-fledged utility apps using standard web technologies like HTML, CSS, JavaScript, JSON, and TXT directly on your device. Run them natively without an internet connection.",
        "Whether you want to copy-paste code from the web or upload entire project files, MyHapps makes the setup effortless. You can build and manage multiple apps at once, effectively turning your phone into a portable development environment.",
        "Advanced users can even integrate Local LLM models to run private, offline AI directly within their mini-apps—no API keys or internet required."
      ],
      features: [
        {icon:"⚡", name:"Multi-File Support", desc:"Work with HTML, CSS, JS, JSON, and TXT files in one project."},
        {icon:"🤖", name:"Local LLM AI", desc:"Run private, offline AI models directly inside your own apps."},
        {icon:"📂", name:"Multi-App Hub", desc:"Create and switch between dozens of custom apps on your device."},
        {icon:"📥", name:"Easy Import", desc:"Copy-paste code or upload files to get started in seconds."},
        {icon:"☁️", name:"Drive Sync", desc:"Backup and restore your custom apps via your personal Google Drive."},
        {icon:"🔒", name:"100% Offline", desc:"Your apps and AI models run locally with total privacy."}
      ],
      support: {
        email: "themyhappslabs@zohomail.in",
        issues: [
          {q:"Code not running?", a:"Ensure your main file is set correctly (e.g. index.html) by tapping the settings icon next to the file."},
          {q:"Limit reached?", a:"Free users can only store 3 apps. Upgrade to premium or delete unused apps."},
          {q:"Permissions blocked?", a:"If your HTML app needs camera/location, make sure to grant the permission when prompted by Android."}
        ]
      },
      privacy: {
        updated: "April 2026",
        sections: [
          {title:"1. Introduction", body:"Welcome to MyHapps. We respect your privacy and are committed to protecting your personal data. This Privacy Policy strictly complies with the Google Play Developer Policy and explains how we handle your information when you use the MyHapps application."},
          {title:"2. Data Collection and Usage", list:["<strong>Account Information:</strong> We collect your email address when you sign in using Google Authentication to securely save your premium status and wallet balance. This data is never shared with third parties.","<strong>User-Generated Content:</strong> Apps you create are stored locally on your device using SQLite. We do NOT upload, monitor, or access your personal app code or data unless you explicitly publish it to the public Discover marketplace.","<strong>Device Permissions:</strong> Some mini-apps you run within MyHapps may request sensitive permissions (Camera, Microphone, or Location). MyHapps handles these dynamically — you will always receive a system prompt before any hardware is accessed. We do not track or store the data generated by your mini-apps."]},
          {title:"3. Advertisements (AdMob)", body:"We use Google AdMob to display advertisements in the free version of the app. AdMob may use advertising IDs and cookies to serve personalized ads.", list:["Google's advertising cookies enable it and its partners to serve ads based on your app usage.","Users may opt out of personalized advertising by visiting Android Settings &gt; Privacy &gt; Ads.","For more information visit <a href='https://policies.google.com/technologies/partner-sites' target='_blank'>Google's Privacy &amp; Terms</a>."]},
          {title:"4. Third-Party Services", body:"We use the following trusted services:", list:["<strong>Google Firebase:</strong> For secure login authentication, points tracking, and storing public marketplace apps.","<strong>Google Drive API:</strong> If you choose to backup your apps, data is saved directly to your personal Google Drive. We cannot access your Drive files outside of the MyHapps folder."]},
          {title:"5. Data Security & Deletion", body:"We take security seriously. Your authentication tokens are handled securely by Google. You have the right to request deletion of your account and associated data directly from within the MyHapps app settings or by contacting us."},
          {title:"6. Children's Privacy", body:"Our application is not directed to children under the age of 13. We do not knowingly collect personal information from children under 13. If we discover that a child under 13 has provided us with personal information, we will delete such information immediately."},
          {title:"7. Contact Us", body:"If you have any questions about this Privacy Policy, please contact us at: <a href='mailto:themyhappslabs@zohomail.in'>themyhappslabs@zohomail.in</a>"}
        ]
      }
    },
    {
      id: "passport-photo",
      name: "Simple Passport Photo Maker",
      icon: "📸",
      tags: ["Free","Android","Offline"],
      short: "Professional passport photos for any country, printed at 600 DPI — straight from your Android phone. No studio needed.",
      link: "https://play.google.com/store/apps/details?id=com.myhappslabs.passportphoto",
      about: [
        "Simple Passport Photo Maker lets you take or select a photo, crop it to the exact passport format for your country, apply professional enhancements, and generate a ready-to-print A4 sheet — all on your device with no data sent anywhere.",
        "Supports standard passport sizes for India, USA, UK, EU, Australia, China, Japan, South Korea and more."
      ],
      features: [
        {icon:"✂️", name:"Smart Crop", desc:"Drag & resize with locked passport aspect ratio for your country's format."},
        {icon:"🖨️", name:"Print-Ready A4", desc:"600 DPI sheet with cut guides, multiple photos per page."},
        {icon:"🌍", name:"All Countries", desc:"35×45mm, 51×51mm, 40×60mm, 33×48mm and many more sizes."},
        {icon:"✨", name:"HD Enhance", desc:"Adjust exposure, clarity, sharpness and smoothness."},
        {icon:"💾", name:"Save JPG / PDF", desc:"Save to gallery or export PDF for professional printing."},
        {icon:"🔒", name:"100% Offline", desc:"No internet needed. Nothing uploaded, ever."}
      ],
      support: {
        email: "themyhappslabs@zohomail.in",
        issues: [
          {q:"PDF not saving?", a:"Go to phone Settings → Apps → Passport Photo Maker → Permissions → allow Storage."},
          {q:"Photo looks blurry?", a:"Use the Sharpness slider in the Enhancements panel before confirming crop."},
          {q:"Wrong photo size?", a:"Select your country's size from the dropdown on the Print Setup screen."},
          {q:"Camera not opening?", a:"Allow Camera permission in phone Settings → Apps → Passport Photo Maker → Permissions."}
        ]
      },
      privacy: {
        updated: "January 2025",
        sections: [
          {title:"1. Information We Collect", body:"Simple Passport Photo Maker does not collect, store, or transmit any personal information or photos. All image processing — cropping, enhancing, generating the print sheet — happens entirely on your device. MyHapps Labs has no access to any photos you take or select within the app."},
          {title:"2. Camera & Storage Permissions", body:"The app requests the following Android permissions, used strictly for these purposes:", list:["<strong>CAMERA</strong> — To let you take a new photo inside the app. Photos are never sent anywhere.","<strong>READ_MEDIA_IMAGES / READ_EXTERNAL_STORAGE</strong> — To let you select an existing photo from your gallery.","<strong>WRITE_EXTERNAL_STORAGE</strong> — To save the finished passport photo sheet to your device. These permissions are not used for any other purpose."]},
          {title:"3. Advertising — Google AdMob", body:"This app displays advertisements served by Google AdMob. AdMob may collect device identifiers and usage data to serve personalized or non-personalized ads. This data collection is governed by Google's own Privacy Policy — not by MyHapps Labs. <a href='https://policies.google.com/privacy' target='_blank'>Google's Privacy Policy</a>."},
          {title:"4. Data Storage & Security", body:"All images you process are saved locally on your device only. No image data, crop data, or output files are transmitted to any server operated by MyHapps Labs. We do not operate any backend servers that receive data from this app."},
          {title:"5. Third-Party Services", body:"Beyond Google AdMob, this app does not integrate any third-party analytics, tracking, crash reporting, or social login services."},
          {title:"6. Children's Privacy", body:"This app is not directed at children under the age of 13. We do not knowingly collect any personal information from children. If you believe a child has provided personal information through this app, please contact us immediately."},
          {title:"7. Your Rights", body:"Since MyHapps Labs does not collect any personal data through this app, there is no personal data for us to provide, correct, or delete. All data (photos and outputs) exist only on your own device and can be deleted by you at any time."},
          {title:"8. Changes to This Policy", body:"We may update this privacy policy from time to time. When we do, we will update the 'Last Updated' date. Continued use of the app after changes are posted constitutes your acceptance of the updated policy."},
          {title:"9. Contact Us", body:"MyHapps Labs · Email: <a href='mailto:themyhappslabs@zohomail.in'>themyhappslabs@zohomail.in</a> · Response time: within 48 hours, Monday to Saturday."}
        ]
      }
    }
  ],

  blogs: [
    {
      id: 1,
      title: "Why Offline-First Apps Matter in 2026",
      date: "May 10, 2026",
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=800",
      excerpt: "In an era of constant connectivity, offline-first apps are the ultimate guarantee of privacy and reliability.",
      content: "Privacy is no longer a luxury — it's a necessity. At MyHapps Labs, we believe your data should never leave your device unless you want it to.\n\nOffline-first apps like MyHapps and Simple Passport Photo Maker ensure that even in remote areas or high-security environments, your tools work without a hitch. By processing everything locally, we eliminate data latency, privacy leaks, and cloud dependency.\n\nIn 2026, with rising data breaches and surveillance concerns, choosing an offline-first app isn't just smart — it's essential."
    },
    {
      id: 2,
      title: "Mastering Passport Photos at Home",
      date: "May 11, 2026",
      image: "https://images.unsplash.com/photo-1551818255-e6e10975bc17?auto=format&fit=crop&q=80&w=800",
      excerpt: "Skip the studio. Here is how to create professional-grade passport photos using just your phone.",
      content: "Most people think you need a studio and expensive lighting for a passport photo. You don't.\n\nWith Simple Passport Photo Maker, all you need is a plain wall and good natural light. Our app handles the exact measurements for 100+ countries, ensuring your application is never rejected due to photo dimensions.\n\nTips for the perfect photo:\n• Use a white or light grey wall as background\n• Stand near a window for natural diffused light\n• Keep a neutral expression\n• The app will crop and align everything automatically"
    },
    {
      id: 3,
      title: "Turning Your Phone into a Dev Lab with MyHapps",
      date: "May 12, 2026",
      image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800",
      excerpt: "Build apps with HTML, CSS, JS, and JSON. Now with Local LLM support for private, offline AI development.",
      content: "Coding on the go used to be a nightmare of bad keyboards and limited previews. MyHapps changes that by providing a high-performance, multi-file environment that fits in your pocket.\n\n### Build Anything with HTML, CSS, JS, and JSON\nMyHapps isn't just for simple scripts. You can build complex, professional-grade tools using standard web technologies. The app fully supports HTML for structure, CSS for styling, JavaScript for logic, and even JSON and TXT for data storage and configuration. Whether you are copy-pasting a snippet from a tutorial or uploading a zip of your latest project, the setup is instant.\n\n### Create and Manage Multiple Apps\nWhy settle for one tool when you can have a full library? MyHapps allows you to create, organize, and switch between dozens of mini-apps. You can build a personal finance tracker, a custom remote control for your smart home, and a specialized task manager—all running natively on your own mobile device hardware.\n\n### The Future: Local LLM AI Integration\nThe most exciting feature in 2026 is the ability to run Local LLM models. You can now build mini-apps that utilize AI for text processing, coding assistance, or data analysis without ever sending a byte of data to the cloud. By running LLMs locally, your AI interactions remain 100% private and function even in the middle of a desert.\n\n### Effortless Workflow\nGetting started is as simple as it gets. You can:\n• **Copy & Paste**: Move code directly from your browser into the MyHapps editor.\n• **File Upload**: Import entire project folders to run them instantly.\n• **Offline Execution**: Once your app is built, it requires zero internet to function.\n\nMyHapps is more than an app; it's a statement that the most powerful development tool you own is the one already in your pocket."
    },
    {
      id: 4,
      title: "Privacy by Design: How We Build Apps",
      date: "May 13, 2026",
      image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800",
      excerpt: "Every line of code we write starts with one question: does this need to go to the cloud?",
      content: "Privacy by design isn't a checkbox for us — it's our development philosophy.\n\nEvery feature we build starts with the question: 'Can we do this locally?' For passport photos — yes. For HTML app execution — yes. For file management — yes.\n\nThe result is apps that work faster (no network round trips), work anywhere (no connectivity required), and respect your rights as a user.\n\nThis approach also means simpler code, fewer points of failure, and a smaller attack surface for any potential security issues."
    }
  ],

  terms: `Terms & Conditions — MyHapps Labs\nLast Updated: 2025\n\n1. Acceptance of Terms\nBy downloading or using any application published by MyHapps Labs on the Google Play Store, you agree to be bound by these Terms and Conditions.\n\n2. Use of Our Apps\nOur apps are provided for personal, non-commercial use. You agree not to:\n• Reverse engineer, decompile, or disassemble any part of our apps\n• Use our apps for any unlawful purpose\n• Reproduce or redistribute our apps without permission\n• Attempt to gain unauthorized access to any system or service\n\n3. Intellectual Property\nAll content, design, code, and branding within MyHapps Labs apps and this website are the property of MyHapps Labs.\n\n4. Advertisements\nSome apps display advertisements served by Google AdMob. Ad behavior is governed by Google's own terms and privacy policy.\n\n5. Disclaimer of Warranties\nOur apps are provided "as is" without warranties of any kind. Use them at your own risk.\n\n6. Limitation of Liability\nMyHapps Labs shall not be liable for any indirect, incidental, or consequential damages from your use of our apps.\n\n7. Privacy\nEach app has its own privacy policy linked on the app's page on this website.\n\n8. Governing Law\nThese terms are governed by the laws of India.\n\n9. Contact\nEmail: themyhappslabs@zohomail.in`,

  contact: "themyhappslabs@zohomail.in"
};
